FROM harbor.umutcan.info/myproject/python-base:3.11




WORKDIR /app

COPY requirements.txt .
RUN pip uninstall -y psycopg2-binary psycopg2 || true && \
    pip install --no-cache-dir -r requirements.txt --index-url=https://pypi.tuna.tsinghua.edu.cn/simple


COPY app.py .

CMD ["python", "app.py"]

