FROM python:3.9-slim
RUN apt-get update && apt-get install -y \
    libpq-dev gcc && \
    rm -rf /var/lib/apt/lists/*
ENV keyvalue=1
WORKDIR /app
COPY requirements.txt /app/
RUN pip install  -r requirements.txt 
COPY . /app/   
EXPOSE 5000
CMD ["python", "app.py"]

